"use client";

import { useRouter } from "next/navigation";
import { useState } from "react";
import { Icon } from "@/components/icons";
import type { Hotel, Profile } from "@/types";

export function AdminManager({ hotels, profiles, demo }: { hotels: Hotel[]; profiles: Profile[]; demo: boolean }) {
  const router = useRouter(); const [busy, setBusy] = useState(""); const [message, setMessage] = useState("");
  async function send(name: string, url: string, form: HTMLFormElement) {
    setBusy(name); setMessage("");
    try { const response = await fetch(url, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(Object.fromEntries(new FormData(form))) }); const result = await response.json() as { error?: string; message?: string }; if (!response.ok) throw new Error(result.error || "Operazione non riuscita"); setMessage(demo ? `${result.message || "Operazione simulata"} (demo)` : result.message || "Operazione completata"); form.reset(); router.refresh(); }
    catch (cause) { setMessage(cause instanceof Error ? cause.message : "Operazione non riuscita"); }
    finally { setBusy(""); }
  }
  return <div className="space-y-5">
    <div className="grid items-start gap-5 xl:grid-cols-2"><section className="panel p-5 sm:p-6"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#eaf5f0] text-[#2f7a64]"><Icon name="hotel" /></span><div><h2 className="font-extrabold">Aggiungi una struttura</h2><p className="text-xs text-[#89928d]">Crea lo spazio prima di invitare l’utente</p></div></div><form className="mt-5 grid gap-3" onSubmit={(event) => { event.preventDefault(); send("hotel", "/api/admin/hotels", event.currentTarget); }}><input className="field" name="name" placeholder="Nome della struttura" required /><input className="field" name="officialSiteUrl" placeholder="https://www.sitohotel.it" type="url" /><button className="button-primary" disabled={Boolean(busy)}><Icon name="plus" size={17} /> {busy === "hotel" ? "Creo…" : "Crea struttura"}</button></form></section>
      <section className="panel p-5 sm:p-6"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#fff0eb] text-[#d65f49]"><Icon name="mail" /></span><div><h2 className="font-extrabold">Invita un utente</h2><p className="text-xs text-[#89928d]">Riceverà l’email per impostare la password</p></div></div><form className="mt-5 grid gap-3" onSubmit={(event) => { event.preventDefault(); send("user", "/api/admin/users", event.currentTarget); }}><input className="field" name="fullName" placeholder="Nome e cognome" required /><input className="field" name="email" placeholder="email@struttura.it" type="email" required /><select className="field" name="hotelId" required><option value="">Scegli la struttura</option>{hotels.map((hotel) => <option value={hotel.id} key={hotel.id}>{hotel.name}</option>)}</select><select className="field" name="role"><option value="hotel_user">Utente struttura</option><option value="admin">Amministratore</option></select><button className="button-primary" disabled={Boolean(busy)}><Icon name="mail" size={17} /> {busy === "user" ? "Invito…" : "Invia invito"}</button></form></section></div>
    {message && <p className="rounded-xl bg-[#eaf5f0] px-4 py-3 text-sm font-bold text-[#2f7a64]">{message}</p>}
    <section className="panel overflow-hidden"><div className="border-b border-[#e7e7df] px-5 py-4"><h2 className="font-extrabold">Utenti attivi</h2><p className="mt-1 text-xs text-[#89928d]">{profiles.length} account</p></div><div className="overflow-x-auto"><table className="w-full min-w-[680px] text-left text-sm"><thead className="bg-[#fbfaf6] text-xs uppercase tracking-wide text-[#89928d]"><tr><th className="px-5 py-3">Utente</th><th className="px-5 py-3">Struttura</th><th className="px-5 py-3">Ruolo</th><th className="px-5 py-3">Stato</th></tr></thead><tbody>{profiles.map((profile) => <tr className="border-t border-[#ecece5]" key={profile.id}><td className="px-5 py-4"><strong className="block">{profile.full_name || "Senza nome"}</strong><span className="text-xs text-[#89928d]">{profile.email}</span></td><td className="px-5 py-4">{hotels.find((hotel) => hotel.id === profile.hotel_id)?.name || "—"}</td><td className="px-5 py-4 capitalize">{profile.role === "admin" ? "Amministratore" : "Utente hotel"}</td><td className="px-5 py-4"><span className={`rounded-full px-2.5 py-1 text-xs font-bold ${profile.active ? "bg-emerald-50 text-emerald-700" : "bg-stone-100 text-stone-600"}`}>{profile.active ? "Attivo" : "Disattivato"}</span></td></tr>)}</tbody></table></div></section>
  </div>;
}
