"use client";

import { useRouter } from "next/navigation";
import { useState } from "react";
import { Icon } from "@/components/icons";

export function KnowledgeManager({ defaultUrl, demo }: { defaultUrl: string; demo: boolean }) {
  const router = useRouter(); const [busy, setBusy] = useState(""); const [message, setMessage] = useState("");
  async function run(name: string, url: string, body: BodyInit, headers?: HeadersInit) {
    setBusy(name); setMessage("");
    try { const response = await fetch(url, { method: "POST", body, headers }); const result = await response.json() as { error?: string; message?: string }; if (!response.ok) throw new Error(result.error || "Operazione non riuscita"); setMessage(result.message || "Fonte aggiunta."); router.refresh(); }
    catch (cause) { setMessage(cause instanceof Error ? cause.message : "Operazione non riuscita"); }
    finally { setBusy(""); }
  }
  return <div className="space-y-3">
    <details className="panel group" open><summary className="flex cursor-pointer list-none items-center gap-3 p-4 sm:p-5"><span className="grid h-10 w-10 place-items-center rounded-xl bg-blue-50 text-blue-700"><Icon name="globe" /></span><div><h3 className="font-extrabold">Sito web ufficiale</h3><p className="text-xs text-[#89928d]">Legge fino a 8 pagine dello stesso dominio</p></div><Icon className="ml-auto transition group-open:rotate-90" name="arrow" size={18} /></summary><form className="grid gap-3 border-t border-[#e7e7df] p-4 sm:grid-cols-[1fr_auto] sm:p-5" onSubmit={(event) => { event.preventDefault(); const form = new FormData(event.currentTarget); run("website", "/api/knowledge/website", JSON.stringify({ url: form.get("url") }), { "Content-Type": "application/json" }); }}><input className="field" defaultValue={defaultUrl} name="url" placeholder="https://www.nomehotel.it" type="url" required /><button className="button-primary" disabled={Boolean(busy)}>{busy === "website" ? "Leggo il sito…" : "Acquisisci sito"}</button></form></details>
    <details className="panel group"><summary className="flex cursor-pointer list-none items-center gap-3 p-4 sm:p-5"><span className="grid h-10 w-10 place-items-center rounded-xl bg-violet-50 text-violet-700"><Icon name="upload" /></span><div><h3 className="font-extrabold">Carica un file</h3><p className="text-xs text-[#89928d]">TXT, Markdown, CSV, JSON o HTML · massimo 5 MB</p></div><Icon className="ml-auto transition group-open:rotate-90" name="arrow" size={18} /></summary><form className="grid gap-3 border-t border-[#e7e7df] p-4 sm:grid-cols-[1fr_auto] sm:p-5" onSubmit={(event) => { event.preventDefault(); run("file", "/api/knowledge/file", new FormData(event.currentTarget)); }}><input className="field file:mr-3 file:rounded-lg file:border-0 file:bg-[#f2f2ed] file:px-3 file:py-1 file:text-xs file:font-bold" name="file" type="file" accept=".txt,.md,.csv,.json,.html,text/plain,text/csv,application/json,text/html" required /><button className="button-primary" disabled={Boolean(busy)}>{busy === "file" ? "Carico…" : "Carica file"}</button></form></details>
    <details className="panel group"><summary className="flex cursor-pointer list-none items-center gap-3 p-4 sm:p-5"><span className="grid h-10 w-10 place-items-center rounded-xl bg-emerald-50 text-emerald-700"><Icon name="file" /></span><div><h3 className="font-extrabold">Aggiungi una nota</h3><p className="text-xs text-[#89928d]">Informazioni operative, servizi, eccezioni o FAQ</p></div><Icon className="ml-auto transition group-open:rotate-90" name="arrow" size={18} /></summary><form className="space-y-3 border-t border-[#e7e7df] p-4 sm:p-5" onSubmit={(event) => { event.preventDefault(); const form = new FormData(event.currentTarget); run("text", "/api/knowledge/text", JSON.stringify({ title: form.get("title"), text: form.get("text") }), { "Content-Type": "application/json" }); }}><input className="field" name="title" placeholder="Titolo, es. Parcheggio e ricarica elettrica" required /><textarea className="field min-h-32" name="text" placeholder="Scrivi solo informazioni corrette e aggiornate…" required /><button className="button-primary" disabled={Boolean(busy)}>{busy === "text" ? "Aggiungo…" : "Aggiungi nota"}</button></form></details>
    {message && <p className={`rounded-xl px-4 py-3 text-sm ${message.toLowerCase().includes("erro") ? "bg-red-50 text-red-700" : "bg-[#eaf5f0] text-[#286b58]"}`} role="status">{demo ? `${message} (modalità demo)` : message}</p>}
  </div>;
}
