import type {
  AppContext,
  Hotel,
  Integration,
  KnowledgeSource,
  Review,
  ToneProfile,
} from "@/types";

export const demoHotel: Hotel = {
  id: "10000000-0000-4000-8000-000000000001",
  name: "Riviera Boutique Hotel",
  slug: "riviera-boutique-hotel",
  official_site_url: "https://example.com",
  default_language: "it",
  timezone: "Europe/Rome",
  active: true,
};

export const demoContext: AppContext = {
  user: { id: "demo-user", email: "demo@rece.local" },
  profile: {
    id: "demo-user",
    hotel_id: demoHotel.id,
    full_name: "Stefano",
    email: "demo@rece.local",
    role: "hotel_user",
    active: true,
  },
  hotel: demoHotel,
  demo: true,
};

export const demoReviews: Review[] = [
  {
    id: "review-1",
    hotel_id: demoHotel.id,
    provider: "google",
    external_id: "google-1",
    author_name: "Francesca R.",
    author_country: "IT",
    rating: 5,
    rating_scale: 5,
    title: null,
    body: "Weekend bellissimo. Camera molto pulita, personale sorridente e colazione con tante torte fatte in casa. Torneremo sicuramente!",
    positive_text: null,
    negative_text: null,
    language: "it",
    review_date: "2026-08-21T09:20:00.000Z",
    source_url: "https://business.google.com/",
    published_reply: null,
    workflow_status: "new",
  },
  {
    id: "review-2",
    hotel_id: demoHotel.id,
    provider: "booking",
    external_id: "booking-2",
    author_name: "Thomas",
    author_country: "DE",
    rating: 8.5,
    rating_scale: 10,
    title: "Great staff, a little noisy",
    body: null,
    positive_text: "The team was incredibly friendly and the location is perfect for the beach.",
    negative_text: "Our room faced the street and was noisy early in the morning.",
    language: "en",
    review_date: "2026-08-20T18:42:00.000Z",
    source_url: "https://admin.booking.com/",
    published_reply: null,
    workflow_status: "drafted",
    latest_draft: {
      id: "draft-2",
      review_id: "review-2",
      generated_text:
        "Dear Thomas, thank you for highlighting our team and location. We are sorry that the street noise affected your rest. For a future stay, please contact us directly: we will gladly suggest one of our quieter rooms. We hope to welcome you back soon.\n\nThe Riviera Boutique Hotel team",
      edited_text: null,
      status: "draft",
      model: "gpt-5-mini",
      created_at: "2026-08-20T18:45:00.000Z",
    },
  },
  {
    id: "review-3",
    hotel_id: demoHotel.id,
    provider: "tripadvisor",
    external_id: "tripadvisor-3",
    author_name: "LucaB79",
    author_country: "IT",
    rating: 3,
    rating_scale: 5,
    title: "Buona posizione, servizi migliorabili",
    body: "Posizione comoda e staff gentile. Il Wi-Fi però era lento e a colazione alcuni prodotti erano già terminati alle 9:30.",
    positive_text: null,
    negative_text: null,
    language: "it",
    review_date: "2026-08-19T12:10:00.000Z",
    source_url: "https://www.tripadvisor.it/",
    published_reply: null,
    workflow_status: "new",
  },
  {
    id: "review-4",
    hotel_id: demoHotel.id,
    provider: "google",
    external_id: "google-4",
    author_name: "Camille",
    author_country: "FR",
    rating: 5,
    rating_scale: 5,
    title: null,
    body: "Un accueil adorable et un hôtel à deux pas de la mer. Mention spéciale pour le petit-déjeuner.",
    positive_text: null,
    negative_text: null,
    language: "fr",
    review_date: "2026-08-18T07:55:00.000Z",
    source_url: "https://business.google.com/",
    published_reply:
      "Merci beaucoup Camille. Nous sommes ravis que l'accueil et le petit-déjeuner vous aient plu!",
    workflow_status: "handled",
  },
  {
    id: "review-5",
    hotel_id: demoHotel.id,
    provider: "booking",
    external_id: "booking-5",
    author_name: "Anonimo",
    author_country: "IT",
    rating: 9,
    rating_scale: 10,
    title: "Ottimo soggiorno in famiglia",
    body: null,
    positive_text: "Pulizia, piscina e gentilezza alla reception.",
    negative_text: "Parcheggio un po' stretto.",
    language: "it",
    review_date: "2026-08-17T16:30:00.000Z",
    source_url: "https://admin.booking.com/",
    published_reply: null,
    workflow_status: "new",
  },
  {
    id: "review-6",
    hotel_id: demoHotel.id,
    provider: "tripadvisor",
    external_id: "tripadvisor-6",
    author_name: "Sara M.",
    author_country: "IT",
    rating: 4,
    rating_scale: 5,
    title: "Una bella scoperta",
    body: "Struttura curata e ottima accoglienza. Suggerirei soltanto più alternative senza glutine.",
    positive_text: null,
    negative_text: null,
    language: "it",
    review_date: "2026-08-16T10:05:00.000Z",
    source_url: "https://www.tripadvisor.it/",
    published_reply: null,
    workflow_status: "handled",
  },
];

export const demoKnowledge: KnowledgeSource[] = [
  {
    id: "knowledge-1",
    hotel_id: demoHotel.id,
    source_type: "website",
    title: "Sito ufficiale",
    source_url: "https://example.com",
    file_name: null,
    status: "ready",
    character_count: 18420,
    error_message: null,
    updated_at: "2026-08-21T08:00:00.000Z",
  },
  {
    id: "knowledge-2",
    hotel_id: demoHotel.id,
    source_type: "file",
    title: "Servizi e FAQ 2026",
    source_url: null,
    file_name: "servizi-faq-2026.txt",
    status: "ready",
    character_count: 6320,
    error_message: null,
    updated_at: "2026-08-19T11:00:00.000Z",
  },
];

export const demoTone: ToneProfile = {
  hotel_id: demoHotel.id,
  formality: 3,
  warmth: 5,
  concision: 4,
  greeting_style: "Nome dell'ospite, quando presente",
  signature: "Lo staff del Riviera Boutique Hotel",
  preferred_words: "accogliere, piacere, cura, vacanza",
  forbidden_words: "problematica, disservizio, colpa",
  extra_instructions:
    "Ringrazia sempre. Sulle critiche riconosci l'esperienza senza contestare e proponi un contatto diretto.",
  example_replies:
    "Grazie Francesca, siamo felici che la cura della camera e la nostra colazione abbiano reso speciale il vostro weekend. A presto!",
};

export const demoIntegrations: Integration[] = [
  {
    id: "integration-google",
    hotel_id: demoHotel.id,
    provider: "google",
    status: "connected",
    external_account_id: "accounts/demo",
    external_location_id: "locations/demo",
    external_location_name: "Riviera Boutique Hotel",
    available_locations: [],
    last_synced_at: "2026-08-22T08:12:00.000Z",
    last_error: null,
  },
  {
    id: "integration-booking",
    hotel_id: demoHotel.id,
    provider: "booking",
    status: "connected",
    external_account_id: null,
    external_location_id: "1234567",
    external_location_name: "Riviera Boutique Hotel",
    available_locations: [],
    last_synced_at: "2026-08-22T08:13:00.000Z",
    last_error: null,
  },
  {
    id: "integration-tripadvisor",
    hotel_id: demoHotel.id,
    provider: "tripadvisor",
    status: "disconnected",
    external_account_id: null,
    external_location_id: null,
    external_location_name: null,
    available_locations: [],
    last_synced_at: null,
    last_error: null,
  },
];
